# Rosenblat's Perceptron

Rosenblat's perceptron included a way to adjust the weights and find the appropriate combination . to overcome the need to modify threshold for each gate seperately, it used a bias term using which neuron can be modified  to implement multiple Boolean functions inn one code.

In [1]:
from random import choice
from numpy import array, dot, random
import numpy as np

### AND Gate

In [2]:
step_function = lambda x : 0 if x < 50 else 1

training_data = [
    (array([0, 0, 1]), 0),
    (array([0, 1, 1]), 0),
    (array([1, 0, 1]), 0),
    (array([1, 1, 1]), 1)
]

w = random.rand(3)
b = 0.1
errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = choice(training_data)
    
    # np.append(w,b)
    result = dot(w,x)
    error = expected - step_function(result)
    errors.append(error)
    w += eta * error * x
    
    
for x,_ in training_data:
    result = dot(x, w)
    
    print('{} : {} -> {}'.format(x[:3], result, step_function(result)))

[0 0 1] : 16.65063470924144 -> 0
[0 1 1] : 33.42227580513096 -> 0
[1 0 1] : 33.36582694671713 -> 0
[1 1 1] : 50.13746804260664 -> 1


### OR Gate

In [3]:
step_function = lambda x : 0 if x < 50 else 1

training_data = [
    (array([0, 0, 1]), 0),
    (array([0, 1, 1]), 1),
    (array([1, 0, 1]), 1),
    (array([1, 1, 1]), 1)
]

w = random.rand(3)
b = 0.1
errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = choice(training_data)
    
    # np.append(w,b)
    result = dot(w,x)
    error = expected - step_function(result)
    errors.append(error)
    w += eta * error * x
    
    
for x,_ in training_data:
    result = dot(x, w)
    
    print('{} : {} -> {}'.format(x[:3], result, step_function(result)))

[0 0 1] : 31.034108969189745 -> 0
[0 1 1] : 51.03951749389512 -> 1
[1 0 1] : 50.016952879511166 -> 1
[1 1 1] : 70.02236140421654 -> 1


### XOR Gate

it is not working for XOR gate.

In [8]:
step_function = lambda x : 0 if x < 50 else 1

training_data = [
    (array([0, 0, 1]), 1),
    (array([0, 1, 1]), 0),
    (array([1, 0, 1]), 0),
    (array([1, 1, 1]), 1)
]

w = random.rand(3)
b = 0.1
errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = choice(training_data)
    
    # np.append(w,b)
    result = dot(w,x)
    error = expected - step_function(result)
    errors.append(error)
    w += eta * error * x
    
    
for x,_ in training_data:
    result = dot(x, w)
    
    print('{} : {} -> {}'.format(x[:3], result, step_function(result)))

[0 0 1] : 50.031905620891074 -> 1
[0 1 1] : 49.93440515637533 -> 0
[1 0 1] : 50.1243255360269 -> 1
[1 1 1] : 50.026825071511155 -> 1


So we have to connect more neuron to each other for XOR Gate called neural network