# Mc Culloh Pitt neuron

In [1]:
from random import choice
from numpy import array, dot, random
import numpy as np

### AND Gate

In [2]:
w = random.rand(2)
w[0] = 1
w[1] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 1)
]

step_function = lambda x: 0 if x < 2 else 1          # Step function with threshold of 2. Anything b

In [3]:
for x, _ in training_data:
    result = dot(x, w)
    
    print('{} : {} -> {}'.format(x[:2], result, step_function(result)))

[0 0] : 0.0 -> 0
[0 1] : 1.0 -> 0
[1 0] : 1.0 -> 0
[1 1] : 2.0 -> 1


### OR Gate

In [7]:
training_data = [
    (array([0, 0]), 0),
    (array([0, 1]), 1),
    (array([1, 0]), 1),
    (array([1, 1]), 1)
]

step_function = lambda x : 0 if x < 1 else 1            # step function with threshold of 1. Anything b 

In [8]:
for x, _ in training_data:
    result = dot(x,w)
    
    print('{} : {} -> {}'.format(x[:2], result,step_function(result)))

[0 0] : 0.0 -> 0
[0 1] : 1.0 -> 1
[1 0] : 1.0 -> 1
[1 1] : 2.0 -> 1
