In [1]:
import numpy as np

# Fully Connected: Forward pass

In [30]:
n = np.random.rand(1, 5)
n

array([[0.65010245, 0.27072573, 0.51346045, 0.39842486, 0.2075666 ]])

In [31]:
class Linear():
    def __init__(self, in_size, out_size):
        self.W = np.random.randn(in_size, out_size) * 0.01
        self.b = np.zeros((1, out_size))
        self.param = [self.W, self.b]
        self.gradA = None
        self.gradB = None
        self.gradInput = None
        
    def forward(self, x):
        self.x = x
        output = np.dot(self.x, self.W) + self.b
        return output

In [32]:
lin = Linear(5, 4)
m = lin.forward(n)

In [33]:
m

array([[ 0.01181388, -0.00672827, -0.01233684, -0.00433824]])

# Fully Connected: Backward pass

In [26]:
#upstream gradient = dm/dn
#upstream gradient = dL/dm (which is nextgrad)
# dm/dn = d(K+n)/dn = W
np.dot(nextgrad, W)

NameError: name 'W' is not defined

In [ ]:
# dL/dW = dL/dm * dm/dW
np.dot(nextgrad, dodw).reshape(4,5)

In [22]:
# jacobian of dm/dW   (4x20)
dodw = np.zeros((4, 20))
st = 0
for i in range(4):
    for j in range(5):
        dodw[i][st] = n[j]
        st = st + 1

ValueError: setting an array element with a sequence.

# Activation function

In [52]:
class ReLU:
    def forward(self,x):
        self.output = np.maximum(x,0)
        return self.output
    
    def Backward(self,nextgrad):
        self.gradInput = nextgrad.copy()
        self.gradInput[self.output > 0] = 1
        return self.gradInput,[]

In [53]:
n = np.random.randn(5,1)

In [54]:
relu = ReLU()
m = relu.forward(n)
m

array([[0.        ],
       [0.61999777],
       [2.04837456],
       [0.        ],
       [0.        ]])

In [55]:
relu.Backward(m)

(array([[0.],
        [1.],
        [1.],
        [0.],
        [0.]]),
 [])

# Softmax

In [56]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis = 1, keepdims = True))
    return exp_x / np.sum(exp_x, axis = 1, keepdims = True)

In [57]:
n = np.array([3.15,5.3,-2.1]).reshape(1,3)
m = softmax(n)

In [58]:
n

array([[ 3.15,  5.3 , -2.1 ]])

In [59]:
m

array([[1.04274135e-01, 8.95178684e-01, 5.47180443e-04]])

# Cross entropy

In [89]:
class CrossEntropy:
    def forward(self,x , y):
        y_idx = y.argmax()
        self.p = softmax(x)
        cross_entropy = -np.log(self.p[y_idx])
        loss = cross_entropy
        return loss
    def backward(self, x, y):
        y_idx = y.argmax()
        grad = softmax(x)
        grad[y_idx] -= 1
        return grad

In [90]:
n1 = np.array([3.15,5.3,-2.1]).reshape(1,3)
n2 = np.array([1,0,0])

In [91]:
ce = CrossEntropy()
ce.forward(n1,n2)

array([2.26073193, 0.11073193, 7.51073193])

In [92]:
ce.backward(n1,n2)

array([[-0.89572586, -0.10482132, -0.99945282]])