In [45]:
import numpy as np

In [46]:
x = np.random.rand(10,4)
x

array([[0.25032653, 0.44431663, 0.47475477, 0.74058667],
       [0.05571838, 0.7684425 , 0.48431223, 0.9073342 ],
       [0.14106157, 0.99045827, 0.55939095, 0.91097546],
       [0.90733275, 0.93793019, 0.26671877, 0.82964321],
       [0.26741586, 0.40262935, 0.34774588, 0.73321619],
       [0.78397244, 0.81515043, 0.61738889, 0.34758541],
       [0.88695802, 0.21376979, 0.23177711, 0.52343711],
       [0.4012491 , 0.14752167, 0.06674193, 0.2703459 ],
       [0.37294722, 0.96275966, 0.88394885, 0.61469898],
       [0.18842749, 0.89633867, 0.60980529, 0.03837778]])

In [47]:
mean = np.array([np.mean(x, axis = 0)])
mean

array([[0.42554094, 0.65793172, 0.45425847, 0.59162009]])

In [48]:
std = np.array([np.std(x , axis = 0)])
std

array([[0.30107841, 0.30728981, 0.22226098, 0.2783141 ]])

In [49]:
mean_repeated = np.repeat(mean, [10], axis = 0)
mean_repeated

array([[0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009],
       [0.42554094, 0.65793172, 0.45425847, 0.59162009]])

In [50]:
std_repeated = np.repeat(std, [10], axis = 0)
std_repeated

array([[0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ],
       [0.30107841, 0.30728981, 0.22226098, 0.2783141 ]])

In [51]:
X = x - mean_repeated
X

array([[-0.17521441, -0.21361509,  0.0204963 ,  0.14896658],
       [-0.36982256,  0.11051078,  0.03005376,  0.31571411],
       [-0.28447937,  0.33252656,  0.10513248,  0.31935537],
       [ 0.48179181,  0.27999847, -0.1875397 ,  0.23802311],
       [-0.15812507, -0.25530237, -0.10651258,  0.1415961 ],
       [ 0.35843151,  0.15721871,  0.16313042, -0.24403468],
       [ 0.46141709, -0.44416193, -0.22248136, -0.06818298],
       [-0.02429184, -0.51041005, -0.38751654, -0.32127419],
       [-0.05259371,  0.30482794,  0.42969038,  0.02307889],
       [-0.23711345,  0.23840696,  0.15554683, -0.55324231]])

In [54]:
X = x / (std_repeated + 0.0000001)
X

array([[0.83143275, 1.44591999, 2.13602293, 2.66097336],
       [0.18506264, 2.5007085 , 2.17902399, 3.26010746],
       [0.46852089, 3.22320463, 2.51681917, 3.27319071],
       [3.01360852, 3.0522648 , 1.20002462, 2.98095895],
       [0.88819314, 1.31025892, 1.56458289, 2.63449076],
       [2.60388048, 2.65270806, 2.77776428, 1.24889572],
       [2.94593605, 0.69566159, 1.04281463, 1.88074166],
       [1.33270591, 0.48007326, 0.30028617, 0.97136942],
       [1.23870425, 3.13306626, 3.97707439, 2.20865115],
       [0.62584172, 2.91691537, 2.74364406, 0.13789372]])