In [29]:
import numpy as np
from numpy import pi

In [2]:
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [3]:
b=np.arange(4)
b

array([0, 1, 2, 3])

In [4]:
c=a-b
c

array([10, 19, 28, 37])

In [6]:
d=10*b
d


array([ 0, 10, 20, 30])

In [7]:
e=np.sin(a)
e

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [8]:
a**2

array([ 100,  400,  900, 1600], dtype=int32)

In [9]:
a<35

array([ True,  True,  True, False])

In [10]:
A=np.array([[1,2],
            [1,0]])

In [11]:
B=np.array([[2,1],
           [0,2]])

In [12]:
A*B

array([[2, 2],
       [0, 0]])

In [13]:
A@B

array([[2, 5],
       [2, 1]])

In [14]:
A.dot(B)

array([[2, 5],
       [2, 1]])

In [15]:
a1=np.ones((2,3),dtype=int)
a1

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
b1=np.random.random((2,3))
b1

array([[0.19131663, 0.54395038, 0.36093854],
       [0.93905681, 0.12729195, 0.68822382]])

In [17]:
a1*=3
a1

array([[3, 3, 3],
       [3, 3, 3]])

In [18]:
b1+=a1
b1

array([[3.19131663, 3.54395038, 3.36093854],
       [3.93905681, 3.12729195, 3.68822382]])

In [19]:
#  a1+=b1    give type error   because  int+float=! float


In [23]:
#typecasting

a=np.ones(3)
a

array([1., 1., 1.])

In [24]:
a.dtype

dtype('float64')

In [28]:
b=np.ones(3,dtype=np.int32)
b

array([1, 1, 1])

In [30]:
c=np.linspace(0,pi,3)
c

array([0.        , 1.57079633, 3.14159265])

In [31]:
d=b+c
d

array([1.        , 2.57079633, 4.14159265])

In [34]:
d.dtype

dtype('float64')

In [35]:
d.dtype.name

'float64'

In [36]:
e=np.exp(c*1j)
e

array([ 1.000000e+00+0.0000000e+00j,  6.123234e-17+1.0000000e+00j,
       -1.000000e+00+1.2246468e-16j])

In [37]:
e.dtype.name

'complex128'

In [38]:
#some inbuilt methods
a=np.random.random((2,3))
a

array([[0.44395153, 0.62110801, 0.68593766],
       [0.93812746, 0.26074281, 0.80553009]])

In [39]:
a.sum()

3.7553975514190183

In [40]:
a.min()

0.26074280629489066

In [41]:
a.max()

0.9381274555129319

In [42]:
a.mean()

0.6258995919031697

In [45]:
a.std()

0.2235417411865497

In [46]:
#axis wise operation

a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [48]:
a.sum(axis=1)

array([ 6, 22, 38])

In [50]:
a.min(axis=1)

array([0, 4, 8])

In [51]:
a.mean(axis=0)

array([4., 5., 6., 7.])

In [52]:
a.mean(axis=1)

array([1.5, 5.5, 9.5])

In [53]:
a.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [54]:
a.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [55]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
a.cumsum(axis=0)    #commutative sum along each column

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

In [57]:
a.cumsum(axis=1)      #commutative sum along each column

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)