In [2]:
import numpy as np

In [3]:
#one dimensional array

a=np.arange(8,17)
a

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16])

In [4]:
a[2]

10

In [5]:
a[3:7]

array([11, 12, 13, 14])

In [6]:
a[1:7:2]

array([ 9, 11, 13])

In [7]:
a[::4]

array([ 8, 12, 16])

In [8]:
a[::-1]

array([16, 15, 14, 13, 12, 11, 10,  9,  8])

In [9]:
for i in a:
    print(i*(1/2.))

4.0
4.5
5.0
5.5
6.0
6.5
7.0
7.5
8.0


In [10]:
#multidimensional array

a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
a[1,2]

7

In [12]:
a[2:,3]

array([13, 18])

In [13]:
a[3:4,2:3]

array([[17]])

In [14]:
a[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [15]:
a[-1,-1]      #last element

19

In [16]:
a[-1]      #last row

array([15, 16, 17, 18, 19])

In [22]:
a[:,-1]      #last column

array([ 4,  9, 14, 19])

In [26]:
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
