In [1]:
import numpy as np

In [2]:
a=np.arange(3)
a

array([0, 1, 2])

In [3]:
b=np.exp(a)
b

array([1.        , 2.71828183, 7.3890561 ])

In [4]:
c=np.sqrt(a)
c

array([0.        , 1.        , 1.41421356])

In [5]:
d=np.add(a,b)
d

array([1.        , 3.71828183, 9.3890561 ])

In [6]:
e=np.add(a,b,d)        #it consider only first two argument.
e

array([1.        , 3.71828183, 9.3890561 ])

In [7]:
# any()  and  all()

np.all([[True,False],[True,True]])

False

In [8]:
 np.all([[True,False],[True,True]],axis=0)

array([ True, False])

In [9]:
 np.all([[True,False],[True,True]],axis=1)

array([False,  True])

In [10]:
 np.any([[True,False],[True,True]])

True

In [11]:
 np.any([[True,False],[True,True]],axis=0)

array([ True,  True])

In [12]:
 np.any([[True,False],[True,True]],axis=1)

array([ True,  True])

In [13]:
np.all([-1, 4, 5])

True

In [14]:
np.all([1.0, np.nan])       # nan=not a number

True

In [15]:
np.all([1,4,0])      # it gives false for 0

False

In [16]:
np.any([1,4,0])  

True

In [17]:
o=np.array(False)
z=np.all([-1, 4, 5],out=o)
z

array(True)

In [18]:
o

array(True)

In [19]:
id(z)

295691769696

In [20]:
id(o)

295691769696

In [21]:
z is o

True

In [22]:
o=np.array(False)
z=np.any([-1, 4, 5],out=o)
z

array(True)

In [23]:
o

array(True)

In [24]:
id(o)

295691813232

In [25]:
id(z)

295691813232

In [26]:
z is o

True

In [27]:
# argmax and argmin

a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
np.argmax(a)

5

In [29]:
np.argmax(a,axis=0)  #Returns the indices of the maximum values along an axis.

array([1, 1, 1], dtype=int64)

In [30]:
np.argmax(a,axis=1)

array([2, 2], dtype=int64)

In [31]:
np.argmin(a)

0

In [32]:
np.argmin(a,axis=0)        ##Returns the indices of the minimum values along an axis.

array([0, 0, 0], dtype=int64)

In [33]:
np.argmin(a,axis=1)

array([0, 0], dtype=int64)

In [34]:
#argsort

b=np.array([2,9,1])
np.argsort(b)

array([2, 0, 1], dtype=int64)

In [41]:
c=np.array([[1,5,0],
            [2,1,8]])


In [42]:
np.argsort(c)

array([[2, 0, 1],
       [1, 0, 2]], dtype=int64)

In [43]:
np.argsort(c,axis=0)

array([[0, 1, 0],
       [1, 0, 1]], dtype=int64)

In [44]:
np.argsort(c,axis=1)

array([[2, 0, 1],
       [1, 0, 2]], dtype=int64)

In [45]:
#ciel

a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])