In [1]:
import numpy as np

In [2]:
a=10*np.random.random((3,4))
a

array([[1.43534347, 7.56975162, 7.15450933, 4.63918205],
       [5.0140928 , 3.56343616, 5.46828784, 4.22504162],
       [3.77279117, 6.20319778, 2.62537958, 6.81889863]])

In [3]:
a=np.floor(10*np.random.random((3,4)))
a

array([[9., 0., 4., 9.],
       [3., 2., 6., 7.],
       [1., 4., 5., 5.]])

In [4]:
a=np.ceil(10*np.random.random((3,4)))
a

array([[ 2.,  4.,  6.,  6.],
       [ 1.,  6.,  8.,  3.],
       [ 6.,  8.,  7., 10.]])

In [5]:
a.ravel()         #flat the array

array([ 2.,  4.,  6.,  6.,  1.,  6.,  8.,  3.,  6.,  8.,  7., 10.])

In [6]:
a.T      #Transpose

array([[ 2.,  1.,  6.],
       [ 4.,  6.,  8.],
       [ 6.,  8.,  7.],
       [ 6.,  3., 10.]])

In [7]:
a.shape

(3, 4)

In [8]:
a.T.shape

(4, 3)

In [9]:
# reshape function returns its argument with a modified shape,
#whereas the ndarray.resize method modifies the array itself

In [10]:
a.resize(2,6)
a

array([[ 2.,  4.,  6.,  6.,  1.,  6.],
       [ 8.,  3.,  6.,  8.,  7., 10.]])

In [14]:
a.reshape(3,4)

array([[ 2.,  4.,  6.,  6.],
       [ 1.,  6.,  8.,  3.],
       [ 6.,  8.,  7., 10.]])

In [15]:
a

array([[ 2.,  4.,  6.,  6.,  1.,  6.],
       [ 8.,  3.,  6.,  8.,  7., 10.]])

In [19]:
#stacking togather different array

a=np.floor(10*np.random.random((2,2)))
a

array([[0., 5.],
       [4., 8.]])

In [20]:
b=np.ceil(10*np.random.random((2,2)))
b

array([[10.,  6.],
       [ 1.,  6.]])

In [22]:
np.hstack((a,b))

array([[ 0.,  5., 10.,  6.],
       [ 4.,  8.,  1.,  6.]])

In [23]:
np.vstack((a,b))

array([[ 0.,  5.],
       [ 4.,  8.],
       [10.,  6.],
       [ 1.,  6.]])